# Generated by Django 3.2.3 on 2021-05-26 13:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name:')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=50, verbose_name='Familyasi')),
                ('phone', models.CharField(max_length=250, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post title:')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Post slug:')),
                ('img', models.ImageField(blank=True, upload_to='post_img/')),
                ('body', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=80, verbose_name='Post author:')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='kie_app.category')),
            ],
            options={
                'verbose_name_plural': 'Hamma postlar',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ManyToManyField(to='kie_app.Posts', verbose_name='nomlar')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
            },
        ),
    ]
