# Generated by Django 3.2.3 on 2021-05-27 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kie_app', '0002_auto_20210526_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 5, 27, 11, 34, 48, 412567, tzinfo=utc), max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordering',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Ordered posts'),
        ),
    ]
