# Generated by Django 3.2.3 on 2021-05-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kie_app', '0003_auto_20210527_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='username',
        ),
    ]
