# Generated by Django 3.2.3 on 2021-05-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kie_app', '0005_ordering_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='uname',
        ),
    ]
